name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # 每月1号运行一次

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2 # 这个 Action 会自动帮你处理
